version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: sh -c "npm i && npm run start:debug"
    volumes:
      - ./server:/code
    ports:
      - "3000:3000"
      - "9229:9229"
